### ISSUE TITLE
Should not replace #select with #find

### ISSUE THREAD

**Issue by skamansam** [tomoya/rubocop-auto-correct#14]
When i run the plugin, it replaces all occurrences of `.select' with`.find`, which alters the symantics and intention of my code. This should not happen. The rubocop linter does not say anything about these needing to be changed.

**Comment by tomoya** [comment]
Hi @skamansam,
Thank you for reporting. Could you show me example code?

**Comment by tomoya** [comment]
I will close this. because the reaction is nothing.
