### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by liquid1982** [tomoya/rubocop-auto-correct#15]
When I run `Rubocop Auto Correct: Current File` i get the following error:

```
warning: parser/current is loading parser/ruby21, which recognizes warning: 2.1.7-compliant syntax, but you are running 2.1.2.
```

I have this config in my `config.cson` file:

```
  "rubocop-auto-correct":
    rubocopCommandPath: "/Users/vincenzo/.rbenv/versions/2.1.2/bin/rubocop"
```

and I am runnin Ruby 2.1.2.

Is this happening to someone else?

**Comment by tomoya** [comment]
That is [parser](https://github.com/whitequark/parser) warning.

Rubocop depend on parser, and parser output warning that you don't use latest Ruby by patch level.

That is here [parser/lib/parser/current.rb](https://github.com/whitequark/parser/blob/72401442432cb7ae1909b1f980b1dab3c4cad422/lib/parser/current.rb#L31)
According to this Ruby version must be 2.1.5 or higher, When you use Ruby 2.1.x
