### ISSUE TITLE
On save auto run moves my "end"(s) to the wrong place

### ISSUE THREAD

**Issue by Lenocam** [tomoya/rubocop-auto-correct#18]
I have autorun on, when I hit save, auto-correct mismatches my 'def' and 'end' indentions when they previously had been correct. If I hit save a second time, the 'end' continues to be indented. When I correct the issue and put the 'def' and 'end' back into proper allignment and hit save again this issue persists.

Before Save:
![image](https://cloud.githubusercontent.com/assets/5050077/11903401/f064bed8-a586-11e5-9ba1-177d667aa39f.png)

After First Save:
![image](https://cloud.githubusercontent.com/assets/5050077/11903412/08fcb270-a587-11e5-8d1b-c327f67e1d1e.png)

After Second Save:
![image](https://cloud.githubusercontent.com/assets/5050077/11903425/215ab948-a587-11e5-878a-8dfc49573f99.png)

**Comment by tomoya** [comment]
Hi @Lenocam,

Thank you for your reporting. I added debug-mode as a new feature.
Please let you update rubocop-auto-correct@1.1.0 and you will enable Debug Mode option. after that, you will try to the same case, and then let me show your received log.

Thank you,

See ref:
![screenshot_2015-12-27_13_25_39](https://cloud.githubusercontent.com/assets/18009/12010813/93c805d8-acf0-11e5-8359-03e89822bb38.png)
