### ISSUE TITLE
Finding which Rubocop path to use

### ISSUE THREAD

**Issue by janwerkhoven** [tomoya/rubocop-auto-correct#24]
Hi,

I had to update Rubocop Command Path to make your package work. In the documentation you may want to add how users can do that. That would have helped me and will probably save other people some time.

For users to find their Rubocop path they can type `which rubocop`

```
which rubocop
/Users/Jan/.rvm/gems/ruby-2.2.3/bin/rubocop
```

Copying that was not enough. I had to replace `/bin` with `/wrappers` to make it work.

For Ruby experts this makes perfect sense, but for me this took quiet a while to figure out.

Thanks for the package!

**Comment by tomoya** [comment]
Hi @janwerkhoven,

Thank you for your nice suggestion.
I will update documentation. But, If you have a time, please send me a pull-request. It makes me happy.

 Thank you,

**Comment by janwerkhoven** [comment]
My suggestion above does not seem to work anymore... I keep getting these errors. Following the URL did not make me any wiser... Do you have any suggestions how to resolve this?

![screen shot 2016-03-17 at 11 12 28 am](https://cloud.githubusercontent.com/assets/4415419/13832539/365acff4-ec31-11e5-9cde-6d7d9409bba4.png)

`warning: parser/current is loading parser/ruby21, which recognizes warning: 2.1.7-compliant syntax, but you are running 2.1.2. warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.`

```
which rubocop
/Users/Jan/.rvm/gems/ruby-2.2.3/bin/rubocop
```

Console says 2.2.3, error says 2.1.7 code, but running 2.1.2... What's going on??

**Comment by tomoya** [comment]
I have not been able to find the cause yet. I need your help. I think you are using RVM. Do your Ruby environments have a difference between global and project local?
If you have it, I guess that there is the cause around it.

**Comment by janwerkhoven** [comment]
1.
`rvm -v`
`rvm 1.27.0 (latest)`

2.
`which rubocop`
`/Users/Jan/.rvm/gems/ruby-2.1.2/bin/rubocop`

3.
`cd` (to exit my project)
`which rubocop`
`sh: command not found: rubocop`

4.
`gem install rubocop`
Resolves this error 👍 

So the Rubocop gem was installed in my Rails project only.
Installing it in my user root, resolved the error.
Your package no longer throws that error.
Now I'm getting these :)

![screen shot 2016-05-17 at 2 48 56 pm](https://cloud.githubusercontent.com/assets/4415419/15311489/b552c1ee-1c3e-11e6-9c46-c6fae736b46a.png)

Getting closer

**Comment by janwerkhoven** [comment]
All right fixed! Had to run `rubocop --auto-gen-config` in the `.rubocop_todo.yml` file in Rails.

**Comment by lacostenycoder** [comment]
I have the version of rubocop installed for my project ( 0.57.2 ), it runs fine from the terminal but I get this when running in 
Atom version 1.53.0
![Screen Shot 2021-01-01 at 11 17 44 AM](https://user-images.githubusercontent.com/6077905/103442324-2730ad80-4c23-11eb-9eaa-a996d7635f6a.jpg)

when I try with path to
```
which rubocop
/Users/lacoste/.rvm/gems/ruby-2.6.4/bin/rubocop
```
I get
![Screen Shot 2021-01-01 at 11 20 37 AM](https://user-images.githubusercontent.com/6077905/103442366-7a0a6500-4c23-11eb-9cf5-a2bc8448f308.jpg)

```
¯\_(ツ)_/¯
```

**Comment by janwerkhoven** [comment]
@lacostenycoder 
My experience was that even though I had `gem 'rubocop'` in `Gemfile`, `rubocop-auto-correct` seems to ignore that version. Instead it's expecting a globally installed gem. Have you tried running `gem install rubocop`?

**Comment by janwerkhoven** [comment]
A good addition to `rubocop-auto-correct` is the [linter-rubocop](https://atom.io/packages/linter-rubocop). The linter highlights errors, warnings and best practice suggestions with links to the rubocop rules. This has helped me understand why certain rules are best practice before auto-correcting them.
