### ISSUE TITLE
Does this respect my .rubocop.yml?

### ISSUE THREAD

**Issue by monkseal** [tomoya/rubocop-auto-correct#25]
Hey, just installed this plugin but wondering if it respects the `.rubocob.yml` for the project I'm working on? 

I have the cop:

```
Style/StringLiterals:
  EnforcedStyle: double_quotes
```

but when I run the Rubocop auto correct, it changes everything to single quotes...

**Comment by tomoya** [comment]
Hi, this package does not check .rubocop.yml yet. I have thought that I want to apply this. But, I do not have time currently :-(

**Comment by monkseal** [comment]
Ok, if I have time I'll work on it and submit a PR.

**Comment by tomoya** [comment]
That's great.
I think that [linter-eslint](https://github.com/AtomLinter/linter-eslint) code is good as a useful reference. Because it uses .eslintrc. Thank you,

**Comment by monkseal** [comment]
@tomoya I must have been doing something wrong the first time because it is now respecting my rubocop.yml file when I run it. I had to open atom from my project directory. Closing this issue. Thanks for the plugin!

**Comment by tomoya** [comment]
Hi, @monkseal,
I got it. Thank you for using my plugin!

**Comment by dogweather** [comment]
Has this been explicitly coded, to check for the `.rubocop.yml` file in the current project?

I get this problem pretty much in all my projects.
