### ISSUE TITLE
rails redirect_to broke

### ISSUE THREAD

**Issue by fidenz-oshan** [tomoya/rubocop-auto-correct#29]
Rubocop rule  "Use `&&` instead of `and`" change this code to broke

``` ruby
redirect_to :back and return
```

after autocorrect

``` ruby
redirect_to :back && return
```

From the Rails Guide:

> Make sure you use **and return** and not **&& return** because while the former will work, the latter will not due to operator precedence in the Ruby Language.

http://guides.rubyonrails.org/layouts_and_rendering.html

**Comment by tomoya** [comment]
We supported `.rubocop.yml`. I guess it will be resolved using `.rubocop.yml`. please try it.
