### ISSUE TITLE
Release Practices

### ISSUE THREAD

**Issue by philoserf** [tomoya/rubocop-auto-correct#33]
I encourage you to include the CHANGELOG and optimally GitHub releases in the release process.

I came by looking for what is new in 1.4 and; while it is easy enough for someone familiar with GitHub and git, understanding what's new may be beyond the skill of some plugin users.

**Comment by tomoya** [comment]
Hi @philoserf,
Sorry, I forgot to update release note when I released this.  Your suggestion is right.
 I should update release note.

Thank you!

**Comment by philoserf** [comment]
@tomoya. No problem. Thanks for the great work.

**Comment by tomoya** [comment]
I have updated release note. Many thanks!
