### ISSUE TITLE
How to stick the notifications?

### ISSUE THREAD

**Issue by wbotelhos** [tomoya/rubocop-auto-correct#39]
Some times the timeout of the balloon is not enough to read and understand the warning. I would like to see the notifications as long as I want.

Thanks.

**Comment by tomoya** [comment]
Hi @wbotelhos,

This package does not provide sticky style notification. But, you can see all notifications data using by debug mode.
1. Turn on debug mode in package configuration.
2. rubocop-auto-correct will correct some fixes.
3. Open console panel in developer tools.
4. You can see notification data as an object like the bellow.

![image](https://cloud.githubusercontent.com/assets/18009/19732394/3583a400-9bd3-11e6-8e2a-75c3683744be.png)

I think this is not you really want. But, this is one of the solutions as quickly hack.
Thank you,

**Comment by wbotelhos** [comment]
Thank you, @tomoya (:
