### ISSUE TITLE
Feature Request - Disable Notifications

### ISSUE THREAD

**Issue by antarr** [tomoya/rubocop-auto-correct#5]
I would be nice to be able to disable the notifications at the end of execution.

**Comment by tomoya** [comment]
Hi, @atbyrd 

Thank you for using my package.

It's a good idea. I will try to provide notification control option.

**Comment by tomoya** [comment]
@atbyrd 

I released v0.7.0, add notification config option.

https://github.com/tomoya/rubocop-auto-correct/releases/tag/v0.7.0

![settings](https://cloud.githubusercontent.com/assets/18009/7906495/31e36f0c-0867-11e5-8184-0bed41927757.png)

Please check it :smile:

**Comment by antarr** [comment]
Cool Thanks

**Comment by antarr** [comment]
For some reason I don't have an option to view settings. I'm on Yosemite. 
![screenshot](https://cloud.githubusercontent.com/assets/974295/7915186/9329ac52-0841-11e5-813a-a12c41cb1588.png)

**Comment by tomoya** [comment]
Your install ver is 0.6.1. so you don't upgrade yet.
Please upgrade to 0.7.0

**Comment by antarr** [comment]
I've upgraded to 0.7.0. I showed the settings button when I logged in but nothing happened when I clicked on it. When I go and view it under installed packages the button is not there.

**Comment by tomoya** [comment]
ummm,
Possibly , Atom package site is stuffed.

If can you use terminal, run `apm update` command in terminal. Or after a while, please try again.

**Comment by antarr** [comment]
I've completley reinstalled atom with only 2 other packages and still no luck.
![screenshot](https://cloud.githubusercontent.com/assets/974295/7915759/4b5faf58-0845-11e5-8063-72dff0674556.png)

**Comment by antarr** [comment]
If I click in the area (box) I can get to settings !

**Comment by tomoya** [comment]
oh, maybe atom's bug?
But, could you find notification check?

**Comment by antarr** [comment]
Yea, the options are available. Seem just find other than the button is missing

**Comment by tomoya** [comment]
I was relieved, that you are using options.
Maybe, settings button issue is atom's problem (cache, etc).

![2015-06-03 13 23 39](https://cloud.githubusercontent.com/assets/18009/7952641/e64177c2-09f3-11e5-90c6-40da00b8a7a5.png)

**Comment by tomoya** [comment]
This issue is closed.

Thank you for first feature request @atbyrd
