### ISSUE TITLE
Invalid auto-run setting

### ISSUE THREAD

**Issue by aki77** [tomoya/rubocop-auto-correct#9]
conflict with activationCommands.

**Comment by tomoya** [comment]
Fix #8

Many thanks :smile:

**Comment by aki77** [comment]
Only one of the activationCommands and autoRun option should be used.

**Comment by tomoya** [comment]
Sorry, I was confused other problem.

Actually, I knew auto run's issue. But, I have no good idea yet. So, I think I will write a "Need to run manually once at window" at README & settings description.
What do you think?

**Comment by aki77** [comment]
I think it's good. :+1:

**Comment by tomoya** [comment]
Thank you!
